### PR TITLE
Added documentation. Closes #50

### LINKED ISSUE #50: (doc) Create and host documentation
We should provide users with a complete and sober documentation hosted on, e.g. Github Pages.

- [ ] Extract doc from readme
- [ ] Use a quick template from GitHub pages
- [ ] Setup the hosting

### PR DESCRIPTION
**Pull request by DCzajkowski**
I have took some time and created full documentation for the plugin. All pages are in markdown and the site is handled by [vuepress](https://vuepress.vuejs.org/).

## Screenshots

---

## To do
- Setup https://wilixlead.github.io/iohook to serve docs based on this guide: https://vuepress.vuejs.org/guide/deploy.html#github-pages
- Setup CI to run deploy-docs.sh by itself

### CODE REVIEW

**Comment by Djiit** [comment]
Great work! Do you need anything from me ? Will check if I have the correct rights here.

**Comment by Djiit** [comment]
Going further, we could setup a iohook.js.org domain. See https://dns.js.org ;)

**Comment by DCzajkowski** [comment]
Awesome that url there! Will you set it up? I could fix the PR to reflect these changes 😉

**Comment by Djiit** [comment]
Ok, @WilixLead we might need your admin permission to enable GitHub Pages

**Comment by Djiit** [comment]
Do you know https://docsify.js.org ? I don't know how it compare to your solution...

**Comment by DCzajkowski** [comment]
It is basically the same, except Vuepress is more customizable, easier to setup etc. Just have a look at vuepress.vuejs.org

**Comment by DCzajkowski** [comment]
If you want, actually, I could whip up a quick server and share with you how these docs look like :)

**Comment by Djiit** [comment]
Thanks but it's ok, you're screenshot is great :). Now we simply need to wait for @WilixLead admin rights ;)

**Comment by DCzajkowski** [comment]
ok, sounds good :) Are you sure you don't want to play around with them? 3 minutes of work for me :P

**Comment by DCzajkowski** [comment]
There you go: https://739f1bf1.ngrok.io
Let me know what you think ;)

**Comment by Djiit** [comment]
It does look great, but I think docsify provide more configuration options and plugins 🤔. But it's basically the same thing and you've done the hard part, let stay like this :)

**Comment by DCzajkowski** [comment]
Since vuepress is new, you may be right. Currently we don't have much docs, so it shouldn't be a problem whatsoever. When we hit a wall, what is awesome, is that we can simply remove `.vuepress` folder and use anything else, but `.md` will work as expected :)

**Comment by Djiit** [comment]
And this is what I like about your solution : plain, simple markdown files!

**Pull request merged**
