### PR TITLE
enable/disable keyboard events

### PR DESCRIPTION
**Pull request by wurikiji**
- Add features to enable/disable keyboard events to be propagated or not.
- Now, iohook.stop() will enable mouse-click/keyboard event propagation. It is more user-friendly.

## Description

- iohook.enableKeyboardPropagation() enables keyboard events to be propagated.
- iohook.disableKeyboardPropagation() disables keyboard events to be propagted.
- iohook.stop() will enable keyboard/mouse-click events to be propagated.

## Motivation and Context

Refer to issue #34 and PR #75. 

## How Has This Been Tested?

MacOSX 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wurikiji** [comment]
This PR is for the reference. I need someone who will test this to other OS like linux and windows. 
And the commit logs are little dirty. So I will clear the logs if I finished the test on all the OS.

**Comment by wurikiji** [comment]
MacOS - tested
Win10+ - tested but code changes are needed
after testing on linux i will make up the codes and repost the PR.

**Comment by wurikiji** [comment]
WSL (windows subsystem for linux) Bash - failed. In fact, iohook does not work. 
Thus, someone who are windows user should use cmd, msys, cygwin or something to run iohook apps.

**Comment by wurikiji** [comment]
package-lock.json has some problems.

Linux X11 - libuiohook does not support propagation settings. Refer to https://github.com/kwhat/libuiohook/issues/57.

**Comment by Djiit** [comment]
Hi there! Thanks for your work !!

To ensure compat with Linux, could you juste check the platform and make the functions no-op, and documenting it ?

**Comment by fidelics** [comment]
>Win10+ - tested but code changes are needed

@wurikiji , It's working for Win10 as for now? If not, how I need to change code?

**Comment by wurikiji** [comment]
@fidelics you can download working version on [my fork](https://gihub.com/wurikiji/iohook)

**Comment by fidelics** [comment]
@wurikiji Thank you! It's awesome

**Comment by wurikiji** [comment]
Close this PR until I finish the test and code cleanup.

**Comment by Djiit** [comment]
Hi there,

Thanks for your work !

**Comment by Introvertuous** [comment]
has this been abandoned?

**Comment by wurikiji** [comment]
@introvertuous You can refer to my fork. It is not in progress, because I am working on other project.

**Comment by Introvertuous** [comment]
@wurikiji were you able to get this working on all platforms? linux is my particular concern.

**Comment by gggiiia** [comment]
@wurikiji id love to see this work come to life

**Comment by alexhulbert** [comment]
https://stackoverflow.com/questions/26715227/app-window-restore-on-keypress/26734577#26734577

**Pull request closed without merging**
